version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA}:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"

  grafana:
    image: grafana/grafana:9.5.14
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 80:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
      - ${GRAFANA_DATA}:/var/lib/grafana
    env_file:
      - ./config.monitoring

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes:
      - ${LOKI_DATA}:/loki
    command: -config.file=/etc/loki/local-config.yaml

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
